spring:
  application:
    name: eureka-server
    config:
      uri: http://localhost:8888

      eureka:
        client:
          serviceUrl:
            defaultZone: http://localhost:8761/eureka/
        instance:
          preferIpAddress: true
          metadataMap:
            instanceId: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}
